name: forma_flutter
description: A nutrition-first Flutter app for meal logging and calorie trends.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0-beta.4
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  fl_chart: ^1.1.1
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
